name: loop
description: "Minimalistic 2D Game & Animation Engine."
version: 0.0.1+6

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/control_core
  control_core: ">=1.3.0"

  # https://pub.dev/packages/vector_math
  vector_math: ">=2.1.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
